openapi: 3.0.3
info:
  title: Order Service API
  description: API for order management
  version: 1.0.0
  contact:
    name: Observability Demo
servers:
  - url: http://localhost:8081
    description: Local development server

paths:
  /api/health:
    get:
      summary: Health check endpoint
      operationId: health
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /api/orders:
    post:
      summary: Create a new order
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Get all orders
      operationId: getAllOrders
      tags:
        - Orders
      responses:
        '200':
          description: List of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'

  /api/orders/{id}:
    get:
      summary: Get a specific order by ID
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - name: id
          in: path
          required: true
          description: The order ID
          schema:
            type: string
            maxLength: 255
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid order ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Order not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - service
      properties:
        status:
          type: string
          example: UP
        service:
          type: string
          example: order-service

    CreateOrderRequest:
      type: object
      required:
        - itemId
        - quantity
      properties:
        itemId:
          type: string
          description: The ID of the item to order
          example: ITEM-123
        quantity:
          type: integer
          description: The quantity to order
          minimum: 1
          maximum: 10000
          example: 5

    OrderResponse:
      type: object
      required:
        - id
        - itemId
        - quantity
        - status
        - createdAt
      properties:
        id:
          type: string
          description: The unique order ID
          example: 550e8400-e29b-41d4-a716-446655440000
        itemId:
          type: string
          description: The ID of the ordered item
          example: ITEM-123
        quantity:
          type: integer
          description: The ordered quantity
          example: 5
        status:
          type: string
          description: The order status
          example: PENDING
          enum:
            - PENDING
            - CONFIRMED
            - SHIPPED
            - DELIVERED
            - CANCELLED
        createdAt:
          type: string
          format: date-time
          description: The order creation timestamp
          example: '2024-01-15T10:30:00'

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: Invalid order ID
